# app/config/parameters.yml
parameters:
  database_driver:   pdo_mysql
  database_host:     127.0.0.1
  database_port:     3306
  database_name:     kaizenacademy
  database_user:     root
  database_password:  null

  mailer_transport:  gmail
  mailer_host:       smtp.gmail.com
  mailer_user:       kaizenacademysndr@gmail.com
  mailer_password:   kaizenacademy
