<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{

    public function findTopPromotion()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM App:Promotion p ORDER BY p.promo DESC'
            )
            ->setMaxResults(1)
            ->getResult();
    }
}
